extend type Mutation {
  """
  ✨ Insert a single `Observation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  observation_insert(
    """
    Data object to insert into the table.
    """
    data: Observation_Data!
  ): Observation_KeyOutput! @fdc_generated(from: "Observation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `QuarantineRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quarantineRecord_insert(
    """
    Data object to insert into the table.
    """
    data: QuarantineRecord_Data!
  ): QuarantineRecord_KeyOutput! @fdc_generated(from: "QuarantineRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Subject` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insert(
    """
    Data object to insert into the table.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Observation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  observation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Observation_Data!]!
  ): [Observation_KeyOutput!]! @fdc_generated(from: "Observation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `QuarantineRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quarantineRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [QuarantineRecord_Data!]!
  ): [QuarantineRecord_KeyOutput!]! @fdc_generated(from: "QuarantineRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Subject` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Observation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Observation`.
  """
  observation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Observation_Data!
  ): Observation_KeyOutput! @fdc_generated(from: "Observation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `QuarantineRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuarantineRecord`.
  """
  quarantineRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: QuarantineRecord_Data!
  ): QuarantineRecord_KeyOutput! @fdc_generated(from: "QuarantineRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Subject` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Observation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Observation`.
  """
  observation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Observation_Data!]!
  ): [Observation_KeyOutput!]! @fdc_generated(from: "Observation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `QuarantineRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `QuarantineRecord`.
  """
  quarantineRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [QuarantineRecord_Data!]!
  ): [QuarantineRecord_KeyOutput!]! @fdc_generated(from: "QuarantineRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Subject` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Observation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Observation` or `null` if not found.
  """
  observation_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Observation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Observation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Observation_Data!
  ): Observation_KeyOutput @fdc_generated(from: "Observation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `QuarantineRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `QuarantineRecord` or `null` if not found.
  """
  quarantineRecord_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: QuarantineRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuarantineRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: QuarantineRecord_Data!
  ): QuarantineRecord_KeyOutput @fdc_generated(from: "QuarantineRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Subject` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Subject` or `null` if not found.
  """
  subject_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Subject_Data!
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Observation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  observation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Observation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Observation_Data!
  ): Int! @fdc_generated(from: "Observation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `QuarantineRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quarantineRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: QuarantineRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: QuarantineRecord_Data!
  ): Int! @fdc_generated(from: "QuarantineRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Subject` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subject_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Subject_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Subject_Data!
  ): Int! @fdc_generated(from: "Subject", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Observation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  observation_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Observation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Observation_FirstRow
  ): Observation_KeyOutput @fdc_generated(from: "Observation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `QuarantineRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quarantineRecord_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: QuarantineRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuarantineRecord_FirstRow
  ): QuarantineRecord_KeyOutput @fdc_generated(from: "QuarantineRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Subject` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subject_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Observation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  observation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Observation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Observation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `QuarantineRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quarantineRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: QuarantineRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Subject` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subject_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Subject_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Subject", purpose: DELETE_MULTIPLE)
}
