extend type Query {
  """
  ✨ Look up a single `Observation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  observation(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Observation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Observation_FirstRow
  ): Observation @fdc_generated(from: "Observation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `QuarantineRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  quarantineRecord(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: QuarantineRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: QuarantineRecord_FirstRow
  ): QuarantineRecord @fdc_generated(from: "QuarantineRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Subject` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  subject(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow
  ): Subject @fdc_generated(from: "Subject", purpose: QUERY_SINGLE)
  """
  ✨ List `Observation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  observations(
    """
    Filter condition to narrow down the query results.
    """
    where: Observation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Observation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Observation_Having
  ): [Observation!]! @fdc_generated(from: "Observation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `QuarantineRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  quarantineRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: QuarantineRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [QuarantineRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: QuarantineRecord_Having
  ): [QuarantineRecord!]! @fdc_generated(from: "QuarantineRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Subject` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  subjects(
    """
    Filter condition to narrow down the query results.
    """
    where: Subject_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Subject_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Subject_Having
  ): [Subject!]! @fdc_generated(from: "Subject", purpose: QUERY_MULTIPLE)
}
