extend type Observation {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Observation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Observation` table.
  """
  _count: Int! @fdc_generated(from: "Observation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `behaviorTypeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  behaviorTypeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.behaviorTypeId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `behaviorType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  behaviorType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.behaviorType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `behaviorValue` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  behaviorValue_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.behaviorValue", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `bodyTemp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bodyTemp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.bodyTemp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `cortisolLevel` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cortisolLevel_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.cortisolLevel", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `cortisolMatrix` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cortisolMatrix_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.cortisolMatrix", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `cortisolUnit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cortisolUnit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.cortisolUnit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `heartRateUnit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  heartRateUnit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.heartRateUnit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `heartRate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  heartRate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.heartRate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `latitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  latitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.latitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `longitude` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  longitude_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.longitude", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `narrative` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  narrative_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.narrative", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `observationMethod` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  observationMethod_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.observationMethod", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `respiratoryRateUnit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  respiratoryRateUnit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.respiratoryRateUnit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `respiratoryRate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  respiratoryRate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.respiratoryRate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `severityScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  severityScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.severityScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `subjectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.subjectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `tempUnit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tempUnit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.tempUnit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Observation` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Observation.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Sum the `bodyTemp` field in the `Observation` table.
  """
  bodyTemp_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.bodyTemp", purpose: QUERY_SUM)
  """
  ✨ Sum the `cortisolLevel` field in the `Observation` table.
  """
  cortisolLevel_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.cortisolLevel", purpose: QUERY_SUM)
  """
  ✨ Sum the `heartRate` field in the `Observation` table.
  """
  heartRate_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Observation.heartRate", purpose: QUERY_SUM)
  """
  ✨ Sum the `latitude` field in the `Observation` table.
  """
  latitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.latitude", purpose: QUERY_SUM)
  """
  ✨ Sum the `longitude` field in the `Observation` table.
  """
  longitude_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.longitude", purpose: QUERY_SUM)
  """
  ✨ Sum the `respiratoryRate` field in the `Observation` table.
  """
  respiratoryRate_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Observation.respiratoryRate", purpose: QUERY_SUM)
  """
  ✨ Sum the `severityScore` field in the `Observation` table.
  """
  severityScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Observation.severityScore", purpose: QUERY_SUM)
  """
  ✨ Average the `bodyTemp` field in the `Observation` table.
  """
  bodyTemp_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.bodyTemp", purpose: QUERY_AVG)
  """
  ✨ Average the `cortisolLevel` field in the `Observation` table.
  """
  cortisolLevel_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.cortisolLevel", purpose: QUERY_AVG)
  """
  ✨ Average the `heartRate` field in the `Observation` table.
  """
  heartRate_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.heartRate", purpose: QUERY_AVG)
  """
  ✨ Average the `latitude` field in the `Observation` table.
  """
  latitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.latitude", purpose: QUERY_AVG)
  """
  ✨ Average the `longitude` field in the `Observation` table.
  """
  longitude_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.longitude", purpose: QUERY_AVG)
  """
  ✨ Average the `respiratoryRate` field in the `Observation` table.
  """
  respiratoryRate_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.respiratoryRate", purpose: QUERY_AVG)
  """
  ✨ Average the `severityScore` field in the `Observation` table.
  """
  severityScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Observation.severityScore", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `bodyTemp` field in the `Observation` table.
  """
  bodyTemp_min: Float @fdc_generated(from: "Observation.bodyTemp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `cortisolLevel` field in the `Observation` table.
  """
  cortisolLevel_min: Float @fdc_generated(from: "Observation.cortisolLevel", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `heartRate` field in the `Observation` table.
  """
  heartRate_min: Int @fdc_generated(from: "Observation.heartRate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `latitude` field in the `Observation` table.
  """
  latitude_min: Float @fdc_generated(from: "Observation.latitude", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `longitude` field in the `Observation` table.
  """
  longitude_min: Float @fdc_generated(from: "Observation.longitude", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `respiratoryRate` field in the `Observation` table.
  """
  respiratoryRate_min: Int @fdc_generated(from: "Observation.respiratoryRate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `severityScore` field in the `Observation` table.
  """
  severityScore_min: Int @fdc_generated(from: "Observation.severityScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `Observation` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "Observation.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `bodyTemp` field in the `Observation` table.
  """
  bodyTemp_max: Float @fdc_generated(from: "Observation.bodyTemp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `cortisolLevel` field in the `Observation` table.
  """
  cortisolLevel_max: Float @fdc_generated(from: "Observation.cortisolLevel", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `heartRate` field in the `Observation` table.
  """
  heartRate_max: Int @fdc_generated(from: "Observation.heartRate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `latitude` field in the `Observation` table.
  """
  latitude_max: Float @fdc_generated(from: "Observation.latitude", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `longitude` field in the `Observation` table.
  """
  longitude_max: Float @fdc_generated(from: "Observation.longitude", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `respiratoryRate` field in the `Observation` table.
  """
  respiratoryRate_max: Int @fdc_generated(from: "Observation.respiratoryRate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `severityScore` field in the `Observation` table.
  """
  severityScore_max: Int @fdc_generated(from: "Observation.severityScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `Observation` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "Observation.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Observation.id", purpose: ENTITY_ID)
}
extend type QuarantineRecord {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "QuarantineRecord", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table.
  """
  _count: Int! @fdc_generated(from: "QuarantineRecord.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table where the `errors` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  errors_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord.errors", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table where the `ingestedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ingestedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord.ingestedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table where the `originalIndex` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  originalIndex_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord.originalIndex", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `QuarantineRecord` table where the `rawPayload` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  rawPayload_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "QuarantineRecord.rawPayload", purpose: QUERY_COUNT)
  """
  ✨ Sum the `originalIndex` field in the `QuarantineRecord` table.
  """
  originalIndex_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "QuarantineRecord.originalIndex", purpose: QUERY_SUM)
  """
  ✨ Average the `originalIndex` field in the `QuarantineRecord` table.
  """
  originalIndex_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "QuarantineRecord.originalIndex", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `ingestedAt` field in the `QuarantineRecord` table.
  """
  ingestedAt_min: Timestamp @fdc_generated(from: "QuarantineRecord.ingestedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `originalIndex` field in the `QuarantineRecord` table.
  """
  originalIndex_min: Int @fdc_generated(from: "QuarantineRecord.originalIndex", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `ingestedAt` field in the `QuarantineRecord` table.
  """
  ingestedAt_max: Timestamp @fdc_generated(from: "QuarantineRecord.ingestedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `originalIndex` field in the `QuarantineRecord` table.
  """
  originalIndex_max: Int @fdc_generated(from: "QuarantineRecord.originalIndex", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "QuarantineRecord.id", purpose: ENTITY_ID)
}
extend type Subject {
  """
  ✨ List `Observation` objects in a one-to-many relationship (where `Observation`.`subject` is this object).
  """
  observations_on_subject(
    """
    Filter condition to narrow down the query results.
    """
    where: Observation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Observation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Observation_Having
  ): [Observation!]! @fdc_generated(from: "Observation.subject", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Subject", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Subject` table.
  """
  _count: Int! @fdc_generated(from: "Subject.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `dogSizeCategory` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dogSizeCategory_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.dogSizeCategory", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `species` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  species_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.species", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Subject.id", purpose: ENTITY_ID)
}
