name: Generate JOSS Draft PDF

permissions:
    contents: read

on:
    push:
        branches: ["master", "main"]
        paths:
            - "paper.md"
            - "paper.bib"
            - ".github/workflows/joss-draft.yml"
    pull_request:
        paths:
            - "paper.md"
            - "paper.bib"

jobs:
    build-draft:
        runs-on: ubuntu-latest
        name: Compile JOSS Manuscript
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Generate PDF using Open Journals Toolchain
              uses: openjournals/openjournals-draft-action@85a18372e48f551d8af9ddb7a747de685fbbb01c # master (2024-07-17)
              with:
                  journal: joss
                  paper-path: paper.md

            - name: Upload PDF Artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: ethopipe-joss-draft
                  path: paper.pdf

