name: Generate JOSS Draft PDF

permissions:
    contents: read

on:
    push:
        branches: ["master", "main"]
        paths:
            - "paper.md"
            - "paper.bib"
            - ".github/workflows/joss-draft.yml"
    pull_request:
        paths:
            - "paper.md"
            - "paper.bib"

jobs:
    build-draft:
        runs-on: ubuntu-latest
        name: Compile JOSS Manuscript
        steps:
            - name: Checkout repository
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Generate PDF using Open Journals Toolchain
              uses: openjournals/openjournals-draft-action@85a18372e48f551d8af9ddb7a747de685fbbb01c # master (2024-07-17)
              with:
                  journal: joss
                  paper-path: paper.md

            - name: Upload PDF Artifact
              uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              with:
                  name: ethopipe-joss-draft
                  path: paper.pdf

