name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Auto Label PR Paths
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on file changes
        uses: actions/labeler@8558b10f2771ec8e0f6c21e6fc85e50529d89a4e # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
